import AvailabilityCalendar from './AvailabilityCalendar';
const bookingUrl='https://www.airbnb.com/rooms/1040656905837979838?unique_share_id=1969906b-75c6-4522-9134-bbb38375fb07&viralityEntryPoint=1&s=76';
const photos=['https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTA0MDY1NjkwNTgzNzk3OTgzOA%3D%3D/original/de20e643-2eab-4685-b377-39519e624764.jpeg?im_w=1440','https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTA0MDY1NjkwNTgzNzk3OTgzOA%3D%3D/original/a73c509d-2758-4898-914c-65fa01cf3459.jpeg?im_w=1200','https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTA0MDY1NjkwNTgzNzk3OTgzOA%3D%3D/original/a675ff01-d780-4db9-a590-f66aec4459c4.jpeg?im_w=1200','https://a0.muscache.com/im/pictures/miso/Hosting-1040656905837979838/original/b9b036ac-f18c-46c2-a271-e34f7ff98c16.jpeg?im_w=1200','https://a0.muscache.com/im/pictures/miso/Hosting-1040656905837979838/original/857113a1-8546-4f68-915b-113461b88eec.jpeg?im_w=1200'];
export default function Home(){return <><header><a className="logo" href="#top">Cliff House <small>Canyon Lake, Texas</small></a><nav><a href="#stay">The stay</a><a href="#amenities">Amenities</a><a href="#gallery">Gallery</a><a href="#availability" className="pill">Availability</a></nav></header><main id="top">
<section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(8,31,37,.82),rgba(8,31,37,.12)),url('${photos[0]}')`}}><div><p className="eyebrow">Waterfront living · Canyon Lake</p><h1>Where lake days linger a little longer.</h1><p>A spacious waterfront retreat for sunsets, slow mornings, and unforgettable time together.</p><a className="button" href="#availability">View availability</a></div><aside><span><b>10</b> guests</span><span><b>3</b> bedrooms</span><span><b>7</b> beds</span><span><b>2.5</b> baths</span></aside></section>
<section className="intro wrap" id="stay"><p className="eyebrow ink">YOUR CANYON LAKE ESCAPE</p><div><h2>A front-row seat to the lake.</h2><p>Cliff House pairs breathtaking vistas and mesmerizing sunsets with comfortable indoor spaces and two decks designed for enjoying the water. Settle in, slow down, and experience your own waterfront getaway.</p></div></section><section className="photo-band"><img src={photos[1]} alt="The deck overlooking Canyon Lake"/></section>
<section className="amenities wrap" id="amenities"><p className="eyebrow ink">MADE FOR EFFORTLESS GETAWAYS</p><h2>The best of the lake, right outside your door.</h2><div className="grid">{[['♨','Private hot tub','Unwind beneath the open sky after a day on the lake.'],['≈','Waterfront setting','Wake up steps from Canyon Lake and wide-open views.'],['⌂','Two scenic decks','Morning coffee, outdoor meals, and golden-hour sunsets.'],['✦','Firepit & grill','Gather at the grill station, then settle around the fire.'],['⌁','Room for ten','Three bedrooms and seven beds for family and friends.'],['⌘','Everyday comforts','Full kitchen, Wi-Fi, free parking, and self check-in.']].map(x=><article key={x[1]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="gallery wrap" id="gallery"><p className="eyebrow ink">A CLOSER LOOK</p><h2>Come for the view. Stay for the feeling.</h2><div>{photos.slice(1).map((p,i)=><img key={p} src={p} alt={`Cliff House property view ${i+1}`}/>)}</div></section><section className="trust"><strong>4.95</strong><span>★★★★★</span><h2>A guest favorite with 98 reviews.</h2><p>Guests love the views, hot tub, outdoor spaces, comfort, and room for the whole family.</p></section>
<section className="booking wrap" id="availability"><div><p className="eyebrow ink">PLAN YOUR STAY</p><h2>See when Cliff House is available.</h2><p>The calendar mirrors the property’s Airbnb availability. Select the booking button to see live pricing and complete your reservation securely on the original listing.</p><ul><li>Calendar displayed on this website</li><li>Booking completed only through Airbnb</li><li>No payment information collected here</li></ul><a className="airbnb-text" href={bookingUrl} target="_blank" rel="noopener noreferrer">Open the official Airbnb listing →</a></div><AvailabilityCalendar/></section>
</main><footer><span>Cliff House at Canyon Lake</span><small>W.O.R.D. Permit #L1891 · © {new Date().getFullYear()}</small></footer></>}
